name: mycocktailrecipe
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  http: ^0.13.4
  path: ^1.8.0
  sqflite: ^2.0.0+4
  flutter_swiper: ^1.1.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "icons/icon.jpg"
